
backend = "resized"
color_space = "labmixed"

palette = "dark"
check_contrast = true

[templates]
quickshell = { template = 'quickshell.json', target = '~/zenflow/quickshell/Settings/Theme.json' }
gtk3 = { template = 'gtk-colors.css', target = "~/.config/gtk-3.0/colors.css"}
gtk4 = { template = 'gtk-colors.css', target = "~/.config/gtk-3.0/colors.css"}

midnight-discord = { template = '~/.config/equibop/midnight-discord.css', target = "~/.config/equibop/themes/midnight.css"}
cava = { template = 'cava-colors', target = "~/.config/cava/config"}
yazi = { template = 'yazi-colors.toml', target = "~/.config/yazi/yazi-colors.toml"}

